In [1]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
final = pd.read_csv('final_with_email.csv')
post_survey = pd.read_csv('post_survey_short.csv')
post_survey.head()

,Unnamed: 0,Username,post_metric,3a,3b,3c,3d,e1,e2,e3,e4,e5,e7,e8,e9,e10
0,0,cheukyil@andrew.cmu.edu,Increasing True Positive Rate;Increasing True ...,5,5,6,6,5,3,5,5,4,7,5,6,6
1,1,claraw@andrew.cmu.edu,Increasing Accuracy;Decreasing disparity betwe...,5,4,6,6,5,3,5,6,5,6,6,6,6
2,2,kwang2@andrew.cmu.edu,Decreasing False Positive Rate;Decreasing Fals...,6,6,6,6,7,3,4,7,3,5,4,3,7
3,3,sanilsar@andrew.cmu.edu,Increasing True Positive Rate;Increasing True ...,7,4,4,4,5,3,4,4,4,6,6,6,6
4,4,njwong@andrew.cmu.edu,Increasing Accuracy;Decreasing disparity betwe...,5,2,5,6,6,3,6,6,2,6,4,5,5

In [6]:
list(post_survey['Username'])

['cheukyil@andrew.cmu.edu',
 'claraw@andrew.cmu.edu',
 'kwang2@andrew.cmu.edu',
 'sanilsar@andrew.cmu.edu',
 'njwong@andrew.cmu.edu',
 'ryankenn@andrew.cmu.edu',
 'azizg@andrew.cmu.edu',
 'amfang@andrew.cmu.edu',
 'jeongkes@andrew.cmu.edu',
 'sjang1@andrew.cmu.edu',
 'ddomalik@andrew.cmu.edu',
 'lmchong@andrew.cmu.edu',
 'awilbour@andrew.cmu.edu',
 'pkhadpe@andrew.cmu.edu',
 'vkamath@andrew.cmu.edu',
 'dgajaraw@andrew.cmu.edu',
 'gzhao@andrew.cmu.edu',
 'charleyz@andrew.cmu.edu',
 'bsheng2@andrew.cmu.edu',
 'pvichiva@andrew.cmu.edu',
 'roshnis@andrew.cmu.edu',
 'ysato@andrew.cmu.edu',
 'cleelama@andrew.cmu.edu',
 'sanag@andrew.cmu.edu',
 'yihaop@andrew.cmu.edu',
 'laiw2@andrew.cmu.edu',
 'jaclyny@andrew.cmu.edu',
 'mingzhe2@andrew.cmu.edu',
 'hsienhuh@andrew.cmu.edu',
 'yiweih@andrew.cmu.edu',
 'tarikaj@andrew.cmu.edu',
 'jx2@andrew.cmu.edu',
 'aroviros@andrew.cmu.edu',
 'liangzhl@andrew.cmu.edu',
 'raajatg@andrew.cmu.edu',
 'ndhuliya@andrew.cmu.edu',
 'araina@andrew.cmu.edu',
 'mnaidu@andrew.cmu.edu',
 'mkomar@andrew.cmu.edu',
 'changc@andrew.cmu.edu',
 'jdiei@andrew.cmu.edu',
 'yunqiaox@andrew.cmu.edu',
 'abonilla@andrew.cmu.edu',
 'nehalg@andrew.cmu.edu',
 'yuhanliu@andrew.cmu.edu',
 'mhasey@andrew.cmu.edu',
 'ashashki@andrew.cmu.edu',
 'pkoppol@andrew.cmu.edu',
 'agyang@andrew.cmu.edu',
 'yunmino@andrew.cmu.edu',
 'yuxilee@andrew.cmu.edu',
 'chenxuli@andrew.cmu.edu',
 'hyunm@andrew.cmu.edu',
 'vzz@andrew.cmu.edu',
 'xiaoyinm@andrew.cmu.edu',
 'acfriedm@andrew.cmu.edu']

In [19]:
left = post_survey[post_survey['Username'].isin(['yihaop@andrew.cmu.edu','yunqiaox@andrew.cmu.edu', 
                                                 'mnaidu@andrew.cmu.edu','roshnis@andrew.cmu.edu'])]
left.head()

,Unnamed: 0,Username,post_metric,3a,3b,3c,3d,e1,e2,e3,e4,e5,e7,e8,e9,e10
20,20,roshnis@andrew.cmu.edu,Increasing True Positive Rate;Increasing True ...,1,2,3,3,2,3,3,3,4,3,4,5,7
24,24,yihaop@andrew.cmu.edu,Decreasing False Positive Rate;Decreasing Fals...,5,5,6,6,5,3,6,6,5,6,5,5,6
37,37,mnaidu@andrew.cmu.edu,Increasing True Positive Rate;Increasing True ...,4,5,4,7,7,3,4,4,5,6,6,4,7
41,41,yunqiaox@andrew.cmu.edu,Increasing Accuracy;Decreasing disparity betwe...,4,5,6,6,6,3,4,4,3,6,6,7,5

In [18]:
final['3a'].isna().sum()

9

In [20]:
new_final = final.merge(left, left_on='Username', right_on='Username' ,how='outer')

In [21]:
new_final.head()

,Unnamed: 0_x,Username,group,Persona,ind_1,ind_2,pre_metric,post_metric_x,pre_quiz,post_quiz,...,3d_y,e1_y,e2_y,e3_y,e4_y,e5_y,e7_y,e8_y,e9_y,e10_y
0,0.0,amfang@andrew.cmu.edu,11,Fairness Advocate,Model_2,Model_4,Maximizing Accuracy,Increasing Accuracy;Decreasing disparity betwe...,0.433962,0.8750,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,jdiei@andrew.cmu.edu,11,Defendent,Model_5,Model_7,"Minimizing False Positive Rate,Maximizing Accu...",Decreasing False Positive Rate;Increasing Accu...,0.820755,1.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,ysato@andrew.cmu.edu,10,Community Member,Model_8,Model_2,"Minimizing disparity (of FPRs\, FNRs\, accurac...",Increasing True Positive Rate;Decreasing False...,0.547170,1.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3.0,ashashki@andrew.cmu.edu,9,Judge,Model_3,Model_7,Maximizing True Positive Rate,Decreasing False Positive Rate;Increasing Accu...,0.716981,0.8750,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.0,cheukyil@andrew.cmu.edu,8,Fairness Advocate,Model_4,Model_4,"Minimizing disparity (of FPRs\, FNRs\, accurac...",Increasing True Positive Rate;Increasing True ...,0.622642,0.8125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN